---
# tasks file for disable-cloud-init
- name: Check folders
  stat:
    path: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
  register: stats

- name: Disable all services in cloud-init
  copy:
    dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
    content: 'datasource_list: [ None ]'    
  register: datasource  
  when: stats.stat.exists

- name: Apply the new configuration 
  command: dpkg-reconfigure -f noninteractive cloud-init
  when: datasource.changed
  changed_when: true
  notify: reboot

- name: Purge package
  apt: 
    purge: yes
    state: absent
    name: cloud-init
  notify: reboot

- name: Delete folders
  file: 
    state: absent
    path: "{{ item }}"
  with_items:
    - "/etc/cloud/"
    - "/var/lib/cloud/"
  notify: reboot
